### ISSUE TITLE
is_safe_url() missing 1 required positional argument: 'allowed_hosts'

### ISSUE THREAD

**Issue by rafrasenberg** [rrmerugu/django-user-registration-bs4#1]
Hi, I am trying your User registration template but getting an error when testing login and signup view on localhost. The error:

`is_safe_url() missing 1 required positional argument: 'allowed_hosts'`

I upgraded to Django 2.1.7

Any quick fix to this?

**Comment by webconexus** [comment]
The problem was the django-allauth version, 0.35 is not compatible with Django 2.1. Solved by upgrading django-allauth to 0.38 though I would let you know.

**Comment by rrmerugu** [comment]
thanks buddy. for pointing out the issue. I'm posting the conversation from the email thread .

>>>The problem was the django-allauth version, 0.35 is not compatible with Django 2.1. Solved by upgrading django-allauth to 0.38 thought I would let you know.
